### ISSUE TITLE
Logerror

### ISSUE THREAD

**Issue by PanikPitty** [JanCraymer/FS22_AdjustableCamera#2]
After lately I repeatedly get messages that indicate an error from the AdjustableCamera, I open this error message and ask for correction in an update. The error is "Error: Invalid customEnvironment given for SpecializationManager.addSpecialization. Should be a string or nil." and generates a LUA call stack.
If a complete log is required, I am happy to provide it.

**Comment by SbSh-DNA-ModDing** [comment]
same here since a year.

**Comment by wieselflinked** [comment]
same here..  :-)

2024-01-19 12:42   Error: Invalid customEnvironment given for SpecializationManager.addSpecialization. Should be a string or nil.
--
  | 477 | 2024-01-19 12:42 LUA call stack:
  | 478 | dataS/scripts/mods.lua (468) : printCallstack
  | 479 | =C:/Users/Frank/Documents/My Games/FarmingSimulator2022/mods/FS22_AdjustableCamera/AdjustableCameraRegister.lua (2) : addSpecialization
  | 480 | =[C] (4294967295)
  | 481 | dataS/scripts/mods.lua (419) : source
  | 482 | dataS/scripts/mods.lua (920) : source
  | 483 | dataS/scripts/xml/XMLFile.lua (296) : closure
  | 484 | dataS/scripts/mods.lua (917) : iterate
  | 485 | dataS/scripts/gui/MPLoadingScreen.lua (765) : loadMod
  | 486 | dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  | 487 | dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  | 488 | dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  | 489 | dataS/scripts/main.lua (1226) : update

**Comment by JanCraymer** [comment]
Fixed with [latest release](https://github.com/JanCraymer/FS22_AdjustableCamera/releases/tag/v1.0.1.0)
