### ISSUE TITLE
Translation bug in keybinding (DE)

### ISSUE THREAD

**Issue by Encaeta** [JanCraymer/FS22_AdjustableCamera#3]
There's a small bug in tranlsation (german) for the keybinding of "move camera up" & "move camera down".
Both entries says the same ("kamera nach unten bewegen") where the first entry must be "move camera UP" / "Kamera nach oben bewegen" 
![Farming Simulator 22 Screenshot 2023 05 25 - 18 09 39 97](https://github.com/JanCraymer/FS22_AdjustableCamera/assets/127420022/cbfac6fb-385c-4f92-9641-a6f8494d159a)

**Comment by JanCraymer** [comment]
Fixed with [latest release](https://github.com/JanCraymer/FS22_AdjustableCamera/releases/tag/v1.0.1.0)
